### ISSUE TITLE
Dont work for me wiht MacOS Sierra

### ISSUE THREAD

**Issue by mikweb2017** [cernst1980/iobroker.hue_scenes#3]
I ran script and all scenes were also detected, but if I did not hit pusch the  button, the scene will not be turned on do I do something wrong?
![hue-1](https://user-images.githubusercontent.com/30271757/38552460-759b9c1a-3cbc-11e8-84c1-132fcf6c679a.PNG)
![hue2](https://user-images.githubusercontent.com/30271757/38552476-7f509d5a-3cbc-11e8-917f-56dd4257c42f.PNG)

**Comment by cernst1980** [comment]
Can you please post the log output for the script / javascript adapter.

**Comment by mikweb2017** [comment]
i have no logs  for / javascript adapter 
I installed everything on ubuntu 16.04 laptop and everything works great
I think it's a problem with MacOs or maybe with node.js 8.1?
to try to do a node.js dowgrade to 6 on the mac

**Comment by mikweb2017** [comment]
solved  Downgrade  to Node.js 6.14.1  und works   now on macOS Sierra
