### ISSUE TITLE
package.json missing

### ISSUE THREAD

**Issue by useful-idiot** [cernst1980/iobroker.hue_scenes#4]
Hi, when I try to install the adapter, npm says

$ ./iobroker url "https://github.com/cernst1980/iobroker.hue_scenes" --debug
install https://github.com/cernst1980/iobroker.hue_scenes/tarball/master
npm install https://github.com/cernst1980/iobroker.hue_scenes/tarball/master --production --prefix "/opt/iobroker" (System call)
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/cernst1980/iobroker.hue_scenes/tarball/master.npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-02T11_28_39_909Z-debug.log

ERROR: Cannot parse /opt/iobroker/node_modules/iobroker.js-controller/adapter/hue_scenes/io-package.json:Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.js-controller/adapter/hue_scenes/io-package.json'
process exited with code 0

I already tried to build one with "npm init" locally and then installing via 
root@raspberrypi:/opt/iobroker# npm install /root/iobroker.hue_scenes  --production --prefix "/opt/iobroker" 

and get 

+ iobroker.hue_scenes-master@1.0.0
updated 1 package in 33.487s

But somehow I am still not successful 

root@raspberrypi:/opt/iobroker# iobroker install iobroker.hue_scenes-master
adapter "hue_scenes-master" yet installed. Use "upgrade" to install newer version.
root@raspberrypi:/opt/iobroker# iobroker upgrade iobroker.hue_scenes-master
Adapter "hue_scenes-master" is not installed.

In the list of adapters it does not show up

**Comment by useful-idiot** [comment]
PS: Output from installer in admin.0 was

$ ./iobroker url "https://github.com/cernst1980/iobroker.hue_scenes" --debug
install https://github.com/cernst1980/iobroker.hue_scenes/tarball/master
npm install https://github.com/cernst1980/iobroker.hue_scenes/tarball/master --production --prefix "/opt/iobroker" (System call)
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/cernst1980/iobroker.hue_scenes/tarball/master.npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-02T11_28_39_909Z-debug.log

ERROR: Cannot parse /opt/iobroker/node_modules/iobroker.js-controller/adapter/hue_scenes/io-package.json:Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.js-controller/adapter/hue_scenes/io-package.json'
process exited with code 0

**Comment by cernst1980** [comment]
Hi,
sorry for confusion, but this is no ioBroker adapter.
It is a javascript file for the ioBroker Script Adapter.
