### ISSUE TITLE
Probleme beim Laden des Hue-Moduls

### ISSUE THREAD

**Issue by Dolphn** [cernst1980/iobroker.hue_scenes#5]
Ich bekomme das node-hue-api Modul nicht geladen. Im Adapter ist es scheibbar hinzugefügt, aber der Befehl `var HueApi = require("node-hue-api");` erzeugt nur diesen Wert:
`{ discovery: { mdnsSearch: [Function: mdnsSearch], nupnpSearch: [Function: nupnpSearch], description: [Function: description] }, ApiError: [Getter], api: { createRemote: [Function: createRemote], createLocal: [Function: createLocal], createInsecureLocal: [Function: createInsecureLocal] }, model: [Getter], time: [Getter], v3: [Getter] }`
Das scheint ein Fehler zu sein, aber ich wüsste nicht, warum der auftreten soll und habe auch nichts dazu im Internet gefunden.
![Screenshot 2023-11-28 165916](https://github.com/cernst1980/iobroker.hue_scenes/assets/61878860/55dc5c61-e5bb-4a4b-81c9-d571e9481ebb)

**Comment by cernst1980** [comment]
Das Skript wird so leider nicht mehr funktionieren.
https://www.npmjs.com/package/node-hue-api#v2-api-compatibility
